#!/usr/bin/env python3
"""Generate docs/reference/tools.md from src/latentforge/tools.py.

Parses the `@tool(...)` decorators via AST (no runtime import needed) and
renders a Markdown reference grouped by the same buckets the CLI uses in
SlashCommands._tools.
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TOOLS_SRC = ROOT / "src" / "latentforge" / "tools.py"
OUT_PATH = ROOT / "docs" / "reference" / "tools.md"

GROUPS: list[tuple[str, list[str]]] = [
    ("Config", ["create_config", "read_config", "update_config", "list_configs"]),
    ("Search", ["search_bing", "search_wikimedia"]),
    ("Download", ["download_images", "download_gallery"]),
    ("Browse", ["list_images", "get_image_info"]),
    ("Organize", ["move_images", "organize_images"]),
    ("Quality", ["analyze_quality", "find_duplicates", "detect_screenshots"]),
    ("Cropping", ["crop_center", "crop_smart", "crop_faces"]),
    ("Faces", ["detect_faces"]),
    ("Training", ["resize_images", "write_caption"]),
    ("Export", ["export_dataset"]),
]


def _annotation_str(node: ast.AST | None) -> str:
    if node is None:
        return "str"
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    try:
        return ast.unparse(node)
    except Exception:
        return "str"


def _literal_str(node: ast.AST) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


def extract_tools(source: str) -> dict[str, dict]:
    tree = ast.parse(source)
    tools: dict[str, dict] = {}

    for node in tree.body:
        if not isinstance(node, ast.AsyncFunctionDef):
            continue
        for deco in node.decorator_list:
            if not (isinstance(deco, ast.Call) and isinstance(deco.func, ast.Name)):
                continue
            if deco.func.id != "tool":
                continue
            args = deco.args
            if len(args) < 2:
                continue
            name = _literal_str(args[0])
            description = _literal_str(args[1])
            if not name or not description:
                continue
            params: list[tuple[str, str]] = []
            if len(args) >= 3 and isinstance(args[2], ast.Dict):
                for k, v in zip(args[2].keys, args[2].values):
                    key = _literal_str(k) if k is not None else None
                    if key is None:
                        continue
                    params.append((key, _annotation_str(v)))
            tools[name] = {"description": description, "params": params}
    return tools


def render(tools: dict[str, dict]) -> str:
    lines: list[str] = []
    lines.append("<!-- AUTO-GENERATED by docs/scripts/gen-api-docs.py — do not edit by hand -->")
    lines.append("<!-- Source: src/latentforge/tools.py -->")
    lines.append("")
    lines.append("# MCP Tools Reference")
    lines.append("")
    lines.append(
        "LatentForge registers the following tools with the Claude agent via a local "
        "MCP server (`create_sdk_mcp_server`). Each tool is an async Python function "
        "decorated with `@tool(name, description, params_schema)` in "
        "[`src/latentforge/tools.py`](https://github.com/utensils/latentforge/blob/main/src/latentforge/tools.py)."
    )
    lines.append("")
    lines.append(
        f"There are **{len(tools)} tools** across {len(GROUPS)} functional groups. "
        "The agent also has the built-in `Read` (with vision), `Write`, and `Bash` tools."
    )
    lines.append("")

    seen: set[str] = set()
    for group_name, tool_names in GROUPS:
        group_tools = [(n, tools[n]) for n in tool_names if n in tools]
        if not group_tools:
            continue
        lines.append(f"## {group_name}")
        lines.append("")
        for name, meta in group_tools:
            seen.add(name)
            lines.append(f"### `{name}`")
            lines.append("")
            lines.append(meta["description"] + ".")
            lines.append("")
            if meta["params"]:
                lines.append("| Parameter | Type |")
                lines.append("| --- | --- |")
                for pname, ptype in meta["params"]:
                    lines.append(f"| `{pname}` | `{ptype}` |")
            else:
                lines.append("_No parameters._")
            lines.append("")

    leftovers = [n for n in tools if n not in seen]
    if leftovers:
        lines.append("## Other")
        lines.append("")
        for name in leftovers:
            meta = tools[name]
            lines.append(f"### `{name}`")
            lines.append("")
            lines.append(meta["description"] + ".")
            lines.append("")
            if meta["params"]:
                lines.append("| Parameter | Type |")
                lines.append("| --- | --- |")
                for pname, ptype in meta["params"]:
                    lines.append(f"| `{pname}` | `{ptype}` |")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    if not TOOLS_SRC.exists():
        print(f"error: source not found at {TOOLS_SRC}", file=sys.stderr)
        return 1
    tools = extract_tools(TOOLS_SRC.read_text())
    if not tools:
        print("error: no @tool decorators found", file=sys.stderr)
        return 1
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render(tools))
    print(f"wrote {OUT_PATH.relative_to(ROOT)} — {len(tools)} tools")
    return 0


if __name__ == "__main__":
    sys.exit(main())
